name: CI

on: 
  workflow_dispatch: {}
  push: {}

jobs:
  has-releasw:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: cocogitto-action
      - name: Initialise repository
        run: |
          git init
          echo 'cocogitto-action/' > .gitignore
          echo '# Mona Lisa' > README.md
          git config --global user.name 'Mona Lisa'
          git config --global user.email 'mona.lisa@example.com'
          git add README.md .gitignore
          git commit -m 'feat: add Mona Lisa docs'
      - name: Run cocogitto-action
        id: release
        uses: ./cocogitto-action
        with:
          check: true
          release: true
      - name: Check outputs
        run: |
          [ "${{ steps.release.outputs.version }}" == '0.1.0' ] || exit 1
